<a href="https://colab.research.google.com/github/HiveCase/MachineLearningPractice/blob/main/Week7/MLP_GA7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Graded Assignment 7

In [1]:
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np
import pandas as pd

##Question 1:
Load the fetch_california_housing dataset from sklearn. Split the data using train_test_split with test_size = 0.2 and random_state as 1. Train the following models using the training data and calculate the R2 Score and Root Mean Squared Error (RMSE) on the test data.

- Model 1: Linear Regression

- Model 2: AdaBoost Regressor with random state = 1

- Model 3: Decision Tree Regressor with random state = 1


Choose the appropriate options:



(A) r2_score (Model 2) > r2_score (Model 1) > r2_score (Model 3)

(B) r2_score (Model 3) > r2_score (Model 1) > r2_score (Model 2)

(C) RMSE (Model 2) > RMSE (Model 1) > RMSE (Model 3)

(D) RMSE (Model 3) > RMSE (Model 1) > RMSE (Model 2)

In [2]:
# Load the dataset
data = fetch_california_housing()
X = data.data
y = data.target

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

###Model 1: Linear Regression

In [3]:
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

r2_lr = r2_score(y_test, y_pred_lr)
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))

###Model 2: AdaBoost Regressor

In [4]:
abr = AdaBoostRegressor(random_state=1)
abr.fit(X_train, y_train)
y_pred_abr = abr.predict(X_test)

r2_abr = r2_score(y_test, y_pred_abr)
rmse_abr = np.sqrt(mean_squared_error(y_test, y_pred_abr))


###Model 3: Decision Tree Regressor

In [5]:
dtr = DecisionTreeRegressor(random_state=1)
dtr.fit(X_train, y_train)
y_pred_dtr = dtr.predict(X_test)

r2_dtr = r2_score(y_test, y_pred_dtr)
rmse_dtr = np.sqrt(mean_squared_error(y_test, y_pred_dtr))


In [6]:
print("Model Performance on Test Set:")
print(f"Linear Regression     -> R²: {r2_lr:.4f}, RMSE: {rmse_lr:.4f}")
print(f"AdaBoost Regressor    -> R²: {r2_abr:.4f}, RMSE: {rmse_abr:.4f}")
print(f"Decision Tree Regressor -> R²: {r2_dtr:.4f}, RMSE: {rmse_dtr:.4f}")


Model Performance on Test Set:
Linear Regression     -> R²: 0.5966, RMSE: 0.7274
AdaBoost Regressor    -> R²: 0.3945, RMSE: 0.8912
Decision Tree Regressor -> R²: 0.6179, RMSE: 0.7080


Common Instructions for questions 2 & 3

---

Load the `Iris Dataset` from sklearn. Split the data using `train_test_split` with `test_size = 0.33` and `random_state` as **1**. Train the `Logistic Regression` model (with random state as 1) on the training data and make predictions on the test data. Print the confusion matrix and the classification report

In [7]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

In [8]:
# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

In [9]:
# Train Logistic Regression
logreg = LogisticRegression(random_state=1, max_iter=200)
logreg.fit(X_train, y_train)

# Make predictions
y_pred = logreg.predict(X_test)

In [10]:
# Confusion Matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

Confusion Matrix:
[[17  0  0]
 [ 0 18  1]
 [ 0  0 14]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        17
  versicolor       1.00      0.95      0.97        19
   virginica       0.93      1.00      0.97        14

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



##Question 2:
How many samples has the model misclassified?

##Question 3:
What is the recall for class 1? [Answer to two decimal places] (Note that the classes are 0 , 1, 2

Common Instructions for questions 4 & 5

---

Load the train subset of `'20newsgroups'` data with `return_X_y = True`. Vectorize X using `TfidfVectorizer`.

In [11]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

# Load training subset
X_raw, y = fetch_20newsgroups(subset='train', return_X_y=True)

In [12]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(X_raw)

##Question 4:
Which of the following options represent the shape of the fitted and transformed data X?

(A) (11310, 130507)

(B) (21314, 190807)

(C) (11514, 160107)

(D) (11314, 130107)

In [13]:
print(X.shape)


(11314, 130107)


##Question 5:
Split the vectorized data and label into train and validation sets using train_test_split with test_size = 0.3 and random_state = 1. Train a MultinomialNB model on the training dataset and compute the score on the validation set. Enter the score obtained.

In [14]:
# Split the vectorized data
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=1)

# Train Multinomial Naive Bayes
model = MultinomialNB()
model.fit(X_train, y_train)

# Evaluate score on validation set
score = model.score(X_val, y_val)
print(score)

0.8273932253313696
